# Configuration for chart-releaser
# See: https://github.com/helm/chart-releaser

# Use pcp.io domain for the Helm repository
index-path: "index.yaml"
pages-branch: "gh-pages"
pages-index-path: "index.yaml"

# Custom configuration for PCP project
repository-url: "https://pcp.io/helm-charts"

# Release settings
release-name-template: "{{ .Name }}-{{ .Version }}"
skip-existing: true