apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "pcp.fullname" . }}
  labels:
    {{- include "pcp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pcp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pcp.serviceAccountName" . }}
      hostNetwork: {{ .Values.hostNetwork }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              # Enable external access for pmcd and pmproxy
              sed -i 's/PMCD_LOCAL=1/PMCD_LOCAL=0/' /etc/sysconfig/pmcd
              sed -i 's/# PMPROXY_LOCAL=1/PMPROXY_LOCAL=0/' /etc/sysconfig/pmproxy
              echo "PCP external access configured"
              # Start systemd as usual
              exec /usr/sbin/init
          ports:
            - name: pmcd-port
              containerPort: {{ .Values.service.ports.pmcd }}
              protocol: TCP
            - name: pmproxy-port
              containerPort: {{ .Values.service.ports.pmproxy }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.persistence.pmlogger.enabled }}
            - name: pmlogger-storage
              mountPath: {{ .Values.persistence.pmlogger.mountPath }}
            {{- end }}
            {{- if .Values.persistence.pmproxy.enabled }}
            - name: pmproxy-storage
              mountPath: {{ .Values.persistence.pmproxy.mountPath }}
            {{- end }}
            {{- if .Values.hostMonitoring.enabled }}
            - name: host-root
              mountPath: {{ .Values.hostMonitoring.mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.persistence.pmlogger.enabled }}
        - name: pmlogger-storage
          hostPath:
            path: {{ .Values.persistence.pmlogger.hostPath }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if .Values.persistence.pmproxy.enabled }}
        - name: pmproxy-storage
          hostPath:
            path: {{ .Values.persistence.pmproxy.hostPath }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if .Values.hostMonitoring.enabled }}
        - name: host-root
          hostPath:
            path: {{ .Values.hostMonitoring.hostPath }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}