apiVersion: v1
kind: Service
metadata:
  name: {{ include "pcp.fullname" . }}
  labels:
    {{- include "pcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.pmcd }}
      targetPort: pmcd-port
      protocol: TCP
      name: pmcd-port
    - port: {{ .Values.service.ports.pmproxy }}
      targetPort: pmproxy-port
      protocol: TCP
      name: pmproxy-port
  selector:
    {{- include "pcp.selectorLabels" . | nindent 4 }}