name: Publish Charts

on:
  push:
    branches:
      - main
    paths:
      - 'pcp/**'
      - 'archive-analysis/**'

env:
  REGISTRY_GHCR: ghcr.io/performancecopilot/helm-charts
  REGISTRY_QUAY: quay.io/performancecopilot-helm-charts

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Add helm repos
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        run: |
          helm registry login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} ${REGISTRY_QUAY}

      - name: Generate version from commit
        id: version
        run: |
          # Use commit short hash as version for development builds
          VERSION="0.1.0-dev.$(git rev-parse --short HEAD)"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"

      - name: Update chart versions
        run: |
          # Update chart versions with dev version
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.VERSION }}/" pcp/Chart.yaml
          sed -i "s/^version:.*/version: ${{ steps.version.outputs.VERSION }}/" archive-analysis/Chart.yaml

          # Also update appVersion to track the commit
          sed -i "s/^appVersion:.*/appVersion: \"${{ steps.version.outputs.VERSION }}\"/" pcp/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ steps.version.outputs.VERSION }}\"/" archive-analysis/Chart.yaml

      - name: Package charts
        run: |
          helm package pcp/
          helm package archive-analysis/

      - name: Push to GitHub Container Registry
        run: |
          helm push pcp-${{ steps.version.outputs.VERSION }}.tgz oci://${REGISTRY_GHCR}
          helm push archive-analysis-${{ steps.version.outputs.VERSION }}.tgz oci://${REGISTRY_GHCR}

      - name: Push to Quay.io
        run: |
          helm push pcp-${{ steps.version.outputs.VERSION }}.tgz oci://${REGISTRY_QUAY}
          helm push archive-analysis-${{ steps.version.outputs.VERSION }}.tgz oci://${REGISTRY_QUAY}
