name: Test Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list)
        id: list
        run: |
          changed=$(ct list --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list.outputs.changed == 'true'
        uses: helm/kind-action@v1.9.0

      - name: Run chart-testing (install)
        if: steps.list.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

  validate-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Validate PCP chart
        run: |
          helm lint ./pcp
          helm template pcp ./pcp --debug

      - name: Validate archive-analysis chart
        run: |
          helm lint ./archive-analysis
          helm template archive-analysis ./archive-analysis --debug

      - name: Test chart with custom values
        run: |
          helm template pcp ./pcp \
            --set hostMonitoring.enabled=true \
            --set hostNetwork=true \
            --set env.HOST_MOUNT="/host" \
            --debug

          helm template archive-analysis ./archive-analysis \
            --set ingress.enabled=true \
            --set service.type=NodePort \
            --set persistence.dashboards.size=32Mi \
            --debug